const TEAM_IDS = {
  CIRNO: 'cirno',
  DAIYOUSEI: 'daiyousei'
};

const TEAM_FULL_HINT =
  '这边人数已经明显领先了。为了维持阵营平衡，请优先加入另一边的小队。';

const ERROR_CODES = {
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  ALREADY_REGISTERED: 'ALREADY_REGISTERED',
  INVALID_CODE: 'INVALID_CODE',
  CODE_ALREADY_USED: 'CODE_ALREADY_USED',
  DUPLICATE_DISPLAY_NAME: 'DUPLICATE_DISPLAY_NAME',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TEAM_JOIN_RESTRICTED: 'TEAM_JOIN_RESTRICTED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_BANNED: 'USER_BANNED',
  ACTION_CLOSED: 'ACTION_CLOSED',
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  STAMINA_NOT_ENOUGH: 'STAMINA_NOT_ENOUGH',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  FORBIDDEN: 'FORBIDDEN'
};

module.exports = {
  ERROR_CODES,
  TEAM_FULL_HINT,
  TEAM_IDS
};
